name: Sum Numbers

on:
  push:
    paths:
      - number.txt

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          python3 app.py
